# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ABOA
email: t.m.1994@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is a static webpage that makes calls to my ABOA api
  and dynamically updates with REAL information :) All information
  displayed is live, and only the admin can add content.
baseurl: "/ABOA" # the subpath of your site, e.g. /blog
url: "https://fire-pls.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:categories/:year/:month/:day/:title
cookies: "/ABOA/assets/js/libraries/cookie.js"
js_file: "/ABOA/assets/js/application.js"
js_partial: "/ABOA/assets/js/partial"
twitter_username: _rsdz
github_username:  fire-pls

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-coffeescript
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
